title: So Yeon Kim # your name (or website title) here
logo: "/images/Picture1.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Ph.D. Candidate of Computer Engineering <br>
  Ajou University, Woncheon-dong, Yeongtong-gu, Suwon-si, Gyeonggi-do, Republic of Korea <br>
  Email: jebi1771@gmail.com
  <br><br>
  My research interests include multi-view learning, network-based analysis, social data mining and biomedical informatics. 
  I've been mostly working on integrating multi-view data using network-based approaches for both social media and bioinformatics area. 
  <br><br>
  <a href="https://scholar.google.com/citations?hl=ko&view_op=list_works&gmla=AJsN-F5EpjrsToSbfcyJzJRikAkuvgoZZss83b1MHQN_VPArdPzJ9I5DKcL-ia3W3qW72H98J3yYMpVCFaeR15afFQbLdLh63Ajwcf5FWnCcMSy6fHgel7rawWlOO87zgGuUnma-RE_I&user=GrpaczMAAAAJ">Google scholar</a> 
  <br><br>
  <a href="https://www.linkedin.com/in/so-yeon-kim/">LinkedIn</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-146834336-1 # your Google Analytics tracking ID here
